language: haskell
ghc:
    - 7.8
before_install:
    - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
    - travis_retry sudo apt-get update
    - travis_retry sudo apt-get install happy-1.19.4 alex-3.1.3 cabal-install-1.22
    - export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:/opt/cabal/1.20/bin:$PATH
    - travis_retry cabal update
    - travis_retry cabal install Cabal
install:
    - travis_retry cabal install --only-dependencies --enable-tests 
